### ISSUE TITLE
Kalau error jangan di hapus main.pdf nya gengsss, kasian orang yang ngebenerin :v

### ISSUE THREAD

**Issue by Difaal21** [KecerdasanBuatan17/KB3C#100]

**Comment by Difaal21** [comment]
Tidak bertanggung jawab anda yaa

**Comment by ilhammariq** [comment]
Kayaknya nggk sengaja dihpus dif, gua tdi nyoba pas error dicompile kehapus sendiri main pdfnya

**Comment by ilhammariq** [comment]
Tpi klo udah error dicompile tetap mau di pull request, anda tidak bertanggung jawab
